#!/usr/bin/env node
/**
 * EOV配置注入脚本 (EOV Config Injection Script)
 * =============================================
 * 读取项目根目录的 .eov 文件，并生成环境变量配置
 * Reads .eov file from project root and generates environment variable configuration
 * 
 * 使用方法 (Usage):
 *   node scripts/inject-eov.js              # 生成 .env.local 文件
 *   node scripts/inject-eov.js --print      # 打印配置信息
 * 
 * 此脚本在构建前运行，确保 .eov 中的配置被正确应用到构建中
 * This script runs before build to ensure .eov config is properly applied
 */

const fs = require('fs');
const path = require('path');

// 获取项目根目录 (Get project root directory)
const projectRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(projectRoot, '..');

// .eov 文件搜索路径列表，按优先级排序 (EOV file search paths in priority order)
// 1. 仓库根目录 (repo root) - 标准位置
// 2. 项目根目录 (project root) - Docker容器内的备选位置
const eovSearchPaths = [
  path.join(repoRoot, '.eov'),     // 标准位置: ../.eov (仓库根目录)
  path.join(projectRoot, '.eov'),  // 备选位置: ./.eov (项目根目录，用于Docker)
];

// 查找可用的 .eov 文件 (Find available .eov file)
function findEovFile() {
  for (const filePath of eovSearchPaths) {
    if (fs.existsSync(filePath)) {
      return filePath;
    }
  }
  return null;
}

const envLocalPath = path.join(projectRoot, '.env.local');

/**
 * 解析EOV文件内容 (Parse EOV file content)
 * @param {string} content - EOV文件内容 (EOV file content)
 * @returns {Object} 解析后的配置对象 (Parsed config object)
 */
function parseEOV(content) {
  const config = {};
  const lines = content.split('\n');

  for (const line of lines) {
    const trimmedLine = line.trim();
    
    // 跳过注释行和空行 (Skip comment lines and empty lines)
    if (trimmedLine.startsWith('#') || trimmedLine === '') {
      continue;
    }

    // 解析 KEY=VALUE 格式 (Parse KEY=VALUE format)
    const equalIndex = trimmedLine.indexOf('=');
    if (equalIndex > 0) {
      const key = trimmedLine.substring(0, equalIndex).trim();
      let value = trimmedLine.substring(equalIndex + 1).trim();
      
      // 移除引号 (Remove surrounding quotes)
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      
      config[key] = value;
    }
  }

  return config;
}

/**
 * 将EOV配置转换为React环境变量格式 (Convert EOV config to React env var format)
 * @param {Object} eovConfig - EOV配置对象 (EOV config object)
 * @returns {Object} React环境变量对象 (React env var object)
 */
function convertToReactEnv(eovConfig) {
  const reactEnv = {};

  // 映射EOV配置到React环境变量 (Map EOV config to React env vars)
  if (eovConfig.API_BASE_URL) {
    reactEnv.REACT_APP_API_URL = eovConfig.API_BASE_URL;
  }
  if (eovConfig.API_VERSION) {
    reactEnv.REACT_APP_API_VERSION = eovConfig.API_VERSION;
  }
  if (eovConfig.API_TIMEOUT) {
    reactEnv.REACT_APP_API_TIMEOUT = eovConfig.API_TIMEOUT;
  }

  return reactEnv;
}

/**
 * 生成.env.local文件内容 (Generate .env.local file content)
 * @param {Object} reactEnv - React环境变量对象 (React env var object)
 * @returns {string} .env.local文件内容 (.env.local file content)
 */
function generateEnvContent(reactEnv) {
  let content = `# 由 inject-eov.js 自动生成 (Auto-generated by inject-eov.js)
# 请勿手动编辑此文件，修改 .eov 文件后重新运行脚本
# Do not edit this file manually, modify .eov file and re-run script
# 生成时间 (Generated at): ${new Date().toISOString()}

`;

  for (const [key, value] of Object.entries(reactEnv)) {
    content += `${key}=${value}\n`;
  }

  return content;
}

/**
 * 主函数 (Main function)
 */
function main() {
  const args = process.argv.slice(2);
  const printOnly = args.includes('--print');

  console.log('📋 EOV配置注入工具 (EOV Config Injection Tool)');
  console.log('='.repeat(50));

  // 查找.eov文件 (Find .eov file)
  const eovFilePath = findEovFile();
  
  // 检查.eov文件是否存在 (Check if .eov file exists)
  if (!eovFilePath) {
    console.error('❌ 错误: 未找到 .eov 文件');
    console.error('   已搜索以下位置:');
    for (const searchPath of eovSearchPaths) {
      console.error(`   - ${searchPath}`);
    }
    console.error('   请在项目根目录或仓库根目录创建 .eov 文件');
    process.exit(1);
  }

  // 读取并解析.eov文件 (Read and parse .eov file)
  console.log(`📂 读取配置文件: ${eovFilePath}`);
  const eovContent = fs.readFileSync(eovFilePath, 'utf-8');
  const eovConfig = parseEOV(eovContent);

  console.log('\n📊 解析到的EOV配置:');
  for (const [key, value] of Object.entries(eovConfig)) {
    console.log(`   ${key} = ${value}`);
  }

  // 转换为React环境变量 (Convert to React env vars)
  const reactEnv = convertToReactEnv(eovConfig);

  console.log('\n🔄 转换后的React环境变量:');
  for (const [key, value] of Object.entries(reactEnv)) {
    console.log(`   ${key} = ${value}`);
  }

  if (printOnly) {
    console.log('\n✅ 打印模式完成');
    return;
  }

  // 生成.env.local文件 (Generate .env.local file)
  const envContent = generateEnvContent(reactEnv);
  fs.writeFileSync(envLocalPath, envContent);

  console.log(`\n✅ 已生成配置文件: ${envLocalPath}`);
  console.log('   请运行 npm run build 或 npm start 应用新配置');
  console.log('='.repeat(50));
}

// 运行主函数 (Run main function)
main();
